#!/bin/bash

NAME=jescs_Phase2Spring24
EVENTS=100000

if [ -d "./$NAME" ]; then rm -rf ./$NAME; fi

# calculate JECs using the fitJECs 
./fitJESCs_phase2 -o ${NAME} -n ${EVENTS}  -b --skip-L1-PFPuppi -j ak4pfpuppiHLT

python3 jescTxtToDBConverter_cfg.py input=${CMSSW_BASE}/src/JMETriggerAnalysis/NTuplizers/test/JESCorrections/${NAME}/ak4pfpuppiHLT/jesc/ output=./${NAME}/DBfile dumpPython=make_db_file_tmp.py

cmsRun make_db_file_tmp.py 

rm make_db_file_tmp.py

## check the db file
conddb --db ./${NAME}/DBfile/Phase2Spring24_MC.db search JetCorr


# Multiple checks plots
# Raw response checks
python3 plot_raw_response_grids_by_eta.py jescs_Phase2Spring24/ak4pfpuppiHLT/plots_step01/histogram_ak4pfpuppiHLTl1_step01.root --alg ak4pfpuppiHLT --normalize

# Check the fits
python3 plot_abs_cor_vs_jetpt_grid.py jescs_Phase2Spring24/ak4pfpuppiHLT/l2p3.root -o AbsCorVsJetPt_grid.pdf --cols 4

# Check responses post-fit
python3 plot_response_grids_by_eta.py ./jescs_Phase2Spring24/ak4pfpuppiHLT/plots_step04/ClosureVsRefPt.root --alg ak4pfpuppiHLT --normalize

